// flow-typed signature: 21e4476219e39ee9ec2f04102aff0c21
// flow-typed version: <<STUB>>/jest-mock-axios_v^3.0.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-mock-axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-mock-axios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-mock-axios/dist/cancel/Cancel' {
  declare module.exports: any;
}

declare module 'jest-mock-axios/dist/cancel/CancelToken' {
  declare module.exports: any;
}

declare module 'jest-mock-axios/dist' {
  declare module.exports: any;
}

declare module 'jest-mock-axios/dist/lib' {
  declare module.exports: any;
}

declare module 'jest-mock-axios/dist/lib/mock-axios-types' {
  declare module.exports: any;
}

declare module 'jest-mock-axios/dist/lib/mock-axios' {
  declare module.exports: any;
}

declare module 'jest-mock-axios/dist/mock-axios-types' {
  declare module.exports: any;
}

declare module 'jest-mock-axios/dist/mock-axios' {
  declare module.exports: any;
}

declare module 'jest-mock-axios/jest.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-mock-axios/dist/cancel/Cancel.js' {
  declare module.exports: $Exports<'jest-mock-axios/dist/cancel/Cancel'>;
}
declare module 'jest-mock-axios/dist/cancel/CancelToken.js' {
  declare module.exports: $Exports<'jest-mock-axios/dist/cancel/CancelToken'>;
}
declare module 'jest-mock-axios/dist/index' {
  declare module.exports: $Exports<'jest-mock-axios/dist'>;
}
declare module 'jest-mock-axios/dist/index.js' {
  declare module.exports: $Exports<'jest-mock-axios/dist'>;
}
declare module 'jest-mock-axios/dist/lib/index' {
  declare module.exports: $Exports<'jest-mock-axios/dist/lib'>;
}
declare module 'jest-mock-axios/dist/lib/index.js' {
  declare module.exports: $Exports<'jest-mock-axios/dist/lib'>;
}
declare module 'jest-mock-axios/dist/lib/mock-axios-types.js' {
  declare module.exports: $Exports<'jest-mock-axios/dist/lib/mock-axios-types'>;
}
declare module 'jest-mock-axios/dist/lib/mock-axios.js' {
  declare module.exports: $Exports<'jest-mock-axios/dist/lib/mock-axios'>;
}
declare module 'jest-mock-axios/dist/mock-axios-types.js' {
  declare module.exports: $Exports<'jest-mock-axios/dist/mock-axios-types'>;
}
declare module 'jest-mock-axios/dist/mock-axios.js' {
  declare module.exports: $Exports<'jest-mock-axios/dist/mock-axios'>;
}
declare module 'jest-mock-axios/jest.config.js' {
  declare module.exports: $Exports<'jest-mock-axios/jest.config'>;
}
